# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 11:14
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.IntegerField()),
                ('day_off_type', models.CharField(choices=[('hy', 'Holiday'), ('vn', 'Vacation'), ('pl', 'Personal')], max_length=2)),
                ('is_paid', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=120, null=True)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Days off',
            },
        ),
        migrations.CreateModel(
            name='DaysOffRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('request_type', models.CharField(choices=[('hy', 'Holiday'), ('vn', 'Vacation'), ('pl', 'Personal')], max_length=2)),
                ('is_paid', models.BooleanField(default=True)),
                ('status', models.CharField(default='Pending', max_length=10)),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
                ('seen', models.BooleanField(default=False)),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Days off requests',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=25, null=True)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('ssn', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Please enter an SSN in the format `999-99-9999`', regex='^\\d{3}-\\d{2}-\\d{4}$')])),
                ('primary_phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Please enter a phone in the format `(999)999-9999`', regex='^\\(\\d{3}\\)\\d{3}-\\d{4}$')])),
                ('secondary_phone', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a phone in the format `(999)999-9999`', regex='^\\(\\d{3}\\)\\d{3}-\\d{4}$')])),
                ('address_street', models.CharField(max_length=40, verbose_name='Street address')),
                ('address_secondary', models.CharField(blank=True, max_length=25, null=True, verbose_name='Secondary address')),
                ('city', models.CharField(max_length=25)),
                ('state', localflavor.us.models.USStateField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AS', 'American Samoa'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('AA', 'Armed Forces Americas'), ('AE', 'Armed Forces Europe'), ('AP', 'Armed Forces Pacific'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('GU', 'Guam'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('MP', 'Northern Mariana Islands'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VI', 'Virgin Islands'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=2)),
                ('postal_code', localflavor.us.models.USZipCodeField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_creates', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_updates', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.CharField(blank=True, max_length=250, null=True)),
                ('summary_weeks', models.IntegerField(blank=True, null=True)),
                ('summary_view', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User settings',
            },
        ),
        migrations.CreateModel(
            name='WorkPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('adjustment', models.IntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=60, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_periods', to='hr.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='daysoffrequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Employee'),
        ),
        migrations.AddField(
            model_name='daysoffrequest',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dayoff',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_off', to='hr.Employee'),
        ),
        migrations.AddField(
            model_name='dayoff',
            name='entered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_off_creates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dayoff',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_off_updates', to=settings.AUTH_USER_MODEL),
        ),
    ]
