# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_dayoff_days_off_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='external_id',
            new_name='payroll_id',
        ),
    ]
